### ISSUE TITLE
cli: Logs `HyperError`

### ISSUE THREAD

**Issue by ecpullen** [bottlerocket-os/bottlerocket-test-system#548]
If a user is watching the logs from a test and the frequency of logs is > ~5 mins, the cli will error with `Unable to get next log from stream: HyperError: error reading a body from connection: error reading a body from connection: timed out`

**Comment by ecpullen** [comment]
Using running the following test should repro this error.
```yaml
apiVersion: testsys.system/v1
kind: Test
metadata:
  name: hello-bones
  namespace: testsys
spec:
  agent:
    name: hello-agent
    image: "example-test-agent:integ"
    keepRunning: false
    configuration:
      mode: Fast
      person: Bones the Cat
      helloCount: 5
      helloDurationMilliseconds: 500000
  resources: []
  dependsOn: []
  ```
